### ISSUE TITLE
Can I force to load stax-api over stax2-api for the part that concern the stax-api ?

### ISSUE THREAD

**Issue by Maatary** [FasterXML/stax2-api#7]
Whenever stax2-api need things that it share with javax.xml.stream stax-api, i would like to force the class loader to user the one from javax.xml.stream. 

In other words eliminating the package ri, and replace it by the equivalent in javax.xml.stream stax-api ?

is there a way to do that ?

**Comment by prb** [comment]
Your best bet is probably to use some Maven magic in your build, e.g., shading in or filtering the classes in the JAR.

**Comment by Maatary** [comment]
Filtering class in jar ? or shading in ? are those the official terms in maven terms. I'm going to look up for it. although if you have some inputs here, that can guide that would help.

**Comment by prb** [comment]
Have a look here:

https://maven.apache.org/plugins/maven-shade-plugin/shade-mojo.html

**Comment by Maatary** [comment]
Which package should be exacly excluded. The only package that represent the partial reference implementation ?

**Comment by cowtowncoder** [comment]
@Maatary I do not quite understand what you are trying to do. Stax2 does not replace anything that comes from basic stax API; it does not include any of those classes. They should be bundled within JDK (starting with Java 6); although on some incomplete Java platforms (Android) they may be missing and need to be included via Maven.

It sounds to me like you are speculating on root cause for breakage that you have. But I am not sure your current hypothesis is viable.
